project4-todo/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project4-todo/todo/todoapp/urls.py
from . import views
from django.urls import path

app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add, name='add'),
    path('delete/<int:t_id>/', views.delete, name='delete'),
    path('cbvdetail/<int:pk>/', views.detail.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.update.as_view(), name='update'),

]

project4-todo/todo/todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

project4-todo/todo/todoapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy

from . models import Task
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import DetailView
# Create your views here.
def home(request):
    obj = Task.objects.all()
    return render(request,'home.html', {'result': obj})
def add(request):

    if request.method=='POST':
        name = request.POST.get('name', '')
        priority = request.POST.get('priority','')
        date = request.POST.get('date','')
        task = Task(name=name, priority=priority, date=date)
        task.save()
        return redirect('/')
    return render(request, 'add.html')

def delete(request, t_id):
    if request.method == 'POST':
        task = Task.objects.get(id=t_id)
        task.delete()
        return redirect('/')

    return render(request, 'delete.html')

class detail(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class update(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:home')

project4-todo/todo/templates/add.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
    <link rel="stylesheet" href="{% static 'form.css' %}">
    <div class="container">
        <h1>Task Entry</h1>
        <form method="POST" class="mb-3 shadow">
            {% csrf_token %}
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" placeholder="Enter your name" required>
            <label for="name">Priority:</label>
            <input type="text" id="priority" name="priority" placeholder="Enter your priority" required>
            <label for="name">Date:</label>
            <input type="date" id="date" name="date" placeholder="Enter the date" required>
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

project4-todo/todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">TODO</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todoapp:home' %}">Home <span class="sr-only">(current)</span></a>
<!--                </li>-->
<!--                 <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Link</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link disabled" href="#">Disabled</a>-->
<!--                </li>-->
            </ul>
            <form class="form-inline my-2 my-lg-0"><input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

project4-todo/todo/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class=" card w-50">
        <div class="card-body">
            <h5 class="card-title">COMPLETED</h5>
            <p class="card-text"> I'm glad we could successfully complete it.</p>
            <input type="submit" style="background-color: #007bff; ">
        </div>
    </div>
</form>
{% endblock %}

project4-todo/todo/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="shadow card text-white bg-primary mb-3" style="max-width: 18rem; margin-left:50px;">
            <div class="card-header">{{ task.priority }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ task.name }}</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <h6 class="card-title">{{ task.date }}</h6>
                <a class="btn btn-warning" href="{% url 'todoapp:delete' task.id %}">Done</a>
                <a class="btn btn-danger" href="{% url 'todoapp:update' task.id %}">Update</a>

            </div>
        </div>
{% endblock %}

project4-todo/todo/templates/home.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
    <link rel="stylesheet" href="{% static 'addbutton.css' %}">
    <div class="card-container">
        <div class="row">
            {% for i in result %}
        <div class="shadow card text-white bg-primary mb-3" style="max-width: 18rem; margin-left:50px;">
            <div class="card-header">{{ i.priority }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ i.name }}</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <h6 class="card-title">{{ i.date }}</h6>
                <a class="btn btn-warning" href="{% url 'todoapp:delete' i.id %}">Done</a>
                <a class="btn btn-success" href="{% url 'todoapp:cbvdetail' i.id %}">View</a>
                <a class="btn btn-danger" href="{% url 'todoapp:update' i.id %}">Update</a>


            </div>
        </div>
        {% endfor %}
        </div>
    </div>
    <a href="{% url 'todoapp:add' %}">
    <button type="button" class="btn btn-primary btn-lg">ADD</button>
    </a>




{% endblock %}

project4-todo/todo/templates/update.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
    <link rel="stylesheet" href="{% static 'form.css' %}">
    <div class="container">
        <h1>Task Entry</h1>
        <form method="POST" class="mb-3 shadow">
            {% csrf_token %}
            <label for="name">Update Name:</label>
            <input type="text" id="name" name="name" placeholder="Enter the name to be update" required>
            <label for="name">Update Priority:</label>
            <input type="text" id="priority" name="priority" placeholder="Enter the priority to be update" required>
            <label for="name">Update Date:</label>
            <input type="date" id="date" name="date" placeholder="Enter the date to be update" required>
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}